#! /bin/sh

echo "save_quicklook $1" 
echo "save_data: $2"
echo "save_netCDF: $3"
echo "save_catalog: $4"
echo "node: $5"
# get current date and year to feed into Matlab
daystr=`date -u +%y%m%d`
year=`date +%Y`
# if the first 20 min of a new day use previous day 
hour=`date -u +%k%M` 
echo "hour = $hour"
if [ $hour -lt 20 ]
then 
 echo finish processing previous day
 daystr=`date +%y%m%d`
fi
echo "daystr = $daystr"
echo "year = $year"
node=\'$5\'
echo "node = ${node}"

# make output dirs
mkdir -p /scr/eldora1/wvdial_1_processed_data
mkdir -p /scr/eldora1/wvdial_2_processed_data
# set the Matlab command
matcmd="addpath $HOME/projDir/dial/MatlabV2; WVDIALProcessingV01_01_function(${daystr},$1,$2,$3,$4,${node}); exit"
# file, save_quicklook, save_data, save_netCDF, save_catalog
cmd="/opt/local/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
echo "cmd = $cmd"
# run the command
eval $cmd

# Note that you need to make the function executable. This is done by 
# changing the file permissions for (owner = 7 = rwx, group = 5 = r-x, and 
# other = 5 = r-x. To do this the key strokes are 
# chmod 755 DIAL_processV02

