#! /bin/csh -f

#get sun cal data
# script needs to be called with start and end date
#"2019 01 01 00 00 00" "2019 01 31 23 59 59"

set START_TIME="$1"
set END_TIME="$2"

ssh rsfdata@hail SpdbXml2Table -params projDir/cal/params/SpdbXml2Table.suncal -start \"$START_TIME\" -end \"$END_TIME\" > /scr/sci/rsfdata/suncal/suncal_results.txt

mv /scr/sci/rsfdata/suncal/suncal_results.txt /scr/sci/romatsch/data/spol/sunCals

set START_NOSPACE=`echo $START_TIME | sed 's/ //g'`
set START1=`echo $START_NOSPACE | awk '{print substr($0,0,8)}'`
set START2=`echo $START_NOSPACE | awk '{print substr($0,9,6)}'`

set END_NOSPACE=`echo $END_TIME | sed 's/ //g'`
set END1=`echo $END_NOSPACE | awk '{print substr($0,0,8)}'`
set END2=`echo $END_NOSPACE | awk '{print substr($0,9,6)}'`

mv /scr/sci/romatsch/data/spol/sunCals/suncal_results.txt "/scr/sci/romatsch/data/spol/sunCals/SunCal_"$START1"_"$START2"_to_"$END1"_"$END2".txt"
