#! /bin/csh

cd $PROJ_DIR/cal/params

setenv SELF_CONSISTENCY_ZDRM_CORRECTION 0.3

RadxPartRain -params RadxPartRain.zdr_bias.sur -debug -start "2015 05 24 00 00 00" -end "2015 06 09 00 00 00" >>& RadxPartRain.zdr_bias.sur.log 

setenv SELF_CONSISTENCY_ZDRM_CORRECTION 0.0

RadxPartRain -params RadxPartRain.zdr_bias.sur -debug -start "2015 06 09 00 00 00" -end "2015 07 17 00 00 00" >>& RadxPartRain.zdr_bias.sur.log 


setenv SELF_CONSISTENCY_ZDRM_CORRECTION 0.3

#RadxPartRain -params RadxPartRain.zdr_bias.rhi -debug -start "2015 05 24 00 00 00" -end "2015 06 09 00 00 00" >>& RadxPartRain.zdr_bias.rhi.log 

setenv SELF_CONSISTENCY_ZDRM_CORRECTION 0.0

#RadxPartRain -params RadxPartRain.zdr_bias.rhi -debug -start "2015 06 09 00 00 00" -end "2015 07 17 00 00 00" >>& RadxPartRain.zdr_bias.rhi.log 



