#! /bin/csh
#

cd /scr/cirrus1/rsfdata/projects

foreach project ( \
    bomb_snowstorm \
    chill \
    cp2_queensland \
    dynamo \
    firestone \
    front \
    ihop \
    improve \
    improveII \
    name \
    pecan \
    relampago \
    rico \
    timrex \
    trmm_climo )
  rsync -av $project rsfdata@snow:/scr/snow1/rsfdata/projects
end
