#! /bin/csh
#

cd /export/sleet2/rsfdata/projects

foreach project ( \
    spicule \
    otrec)
  rsync -av --exclude time_series --exclude time_series_netcdf $project rsfdata@cirrus:/export/cirrus2/rsfdata/projects
end

