#! /bin/csh
#

cd /export/virga1/rsfdata/projects

rsync -av --exclude time_series --exclude time_series_netcdf spicule rsfdata@cirrus:/export/cirrus2/rsfdata/projects

cd /export/virga2/rsfdata/projects

rsync -av socrates rsfdata@cirrus:/export/sleet3/rsfdata/projects


