#! /bin/csh

cd $PROJ_DIR/system/scripts

./git_backups_https.py --debug --targetDir /scr/sleet1/rsfdata/git_backups |& \
	LogFilter -d $ERRORS_LOG_DIR -p git_backups.py -i daily >& /dev/null &
endif

