#! /bin/csh
#

rsync_dial_data_from_field.py --debug \
    --rsyncSource rsync://166.164.215.174/wvdial1/ \
    --targetDir /export/eldora1/wvdial_1_data |& \
    LogFilter -d $ERRORS_LOG_DIR -p rsync_dial_data_from_field.dial1 -i cron >& /dev/null &

rsync_dial_data_from_field.py --debug \
    --rsyncSource rsync://128.117.47.87/wvdial2/ \
    --targetDir /export/eldora1/wvdial_2_data |& \
    LogFilter -d $ERRORS_LOG_DIR -p rsync_dial_data_from_field.dial2 -i cron >& /dev/null &

