#!/bin/csh

# get LTG data from UW using wget

mkdir -p $DATA_DIR/relampago/raw/wwlln
cd $DATA_DIR/relampago/raw/wwlln

wget -nd -nc -c -r \
    --user=relampago --password=BrodzikWWLLN \
    http://wwlln.net/relampago/


