#!/bin/sh
DEST=/export/hail2/rsfdata/pecan/images/spol_cams
for dir in north south east west
do
  echo starting $dir
  rsync -avz -e "ssh -q -o 'BatchMode yes' -i /home/rsfdata/.ssh/id_rsa_camera -p 20022" \
	  camera@spol.dyndns.org:/data/spol/spol_cams/$dir/ $DEST/$dir
done
